back-end/V1/api/urls.py
from django.urls import path
from .views import getArtByExhibition, getExhibition
'the urls setting for api so the request can send to some specific urls'
urlpatterns = [
    path('/exhibition/<str:pk>/', getArtByExhibition),
    path('/exhibition/', getExhibition),
]

back-end/V1/guideXP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api',include('api.urls')),
    path('', include('guideXP_admin.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back-end/V1/guideXP_admin/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

'''set the url path to the different options'''
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='guideXP_admin/login.html',redirect_authenticated_user=True), name='admin-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='guideXP_admin/logout.html'), name='admin-logout'),
    path('home/',views.home, name='admin-home'),
    path('setting/profile/',views.profile, name='admin-profile'),
    path('setting/account', views.createAccount, name='admin-create-account'),
    path('upload/art/', views.createArt, name='admin-upload-art'),
    path('upload/artist/', views.createArtist, name='admin-upload-artist'),
]

back-end/V1/guideXP_admin/models.py
from django.db import models
from django.contrib.auth.models import User
User._meta.get_field('email').blank = False

'''This is the original database in the last semester, and we will change this in this semester, such as deleting
some useless tables and create new relations about languages, or we may re-build the database'''
class Guidexpuser(models.Model):
    USER_TYPES = (('1', 'Superuser'),('2', 'Admin'),('3', 'Worker'))
    user_type  = models.CharField(max_length=1, choices=USER_TYPES)
    # django has built in User table that we could use, which includes common fields such as
    # username,password, email.
    user       = models.OneToOneField(User, on_delete=models.CASCADE)


class Artist(models.Model):
    artist_img           = models.ImageField(upload_to="artist_images/",null=True, blank=True)
    artist_name          = models.CharField(max_length=70)
    artist_description   = models.TextField(blank=True, null=True)
    artist_uploaded_by   = models.ForeignKey(Guidexpuser, models.CASCADE, related_name='upload_artist')
    artist_authorised_by = models.ForeignKey(Guidexpuser, models.CASCADE, related_name='authorise_artist', null=True, blank=True)

class Exhibition(models.Model):
    exhibition_name           = models.CharField(max_length=50)
    exhibition_uploaded_by    = models.ForeignKey(Guidexpuser, models.CASCADE, related_name='upload_exhibition')
    exhibition_authorised_by  = models.ForeignKey(Guidexpuser, models.CASCADE, related_name='authorise_exhibition', null=True,blank=True)

class Artimage(models.Model):
    art_name          = models.CharField(max_length=255)
    art_description   = models.TextField()
    art_img           = models.ImageField(upload_to="art_images/")
    art_audio         = models.FileField(upload_to="art_audios/")
    art_in_exhibition = models.ForeignKey(Exhibition, models.CASCADE, blank=True, null=True)
    art_from_artist   = models.ForeignKey(Artist, models.CASCADE, blank=True, null=True)
    art_uploaded_by   = models.ForeignKey(Guidexpuser, models.CASCADE, related_name='upload_art')
    art_authorised_by = models.ForeignKey(Guidexpuser, models.CASCADE, related_name='authorise_art', null=True, blank=True)

back-end/V1/guideXP_admin/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *

'''Create the upload functions (this is the original idea, we may change some functions)'''
class UploadArtForm(forms.ModelForm):
    class Meta:
        model = Artimage
        exclude = ['art_uploaded_by','art_authorised_by', 'art_in_gallery', 'art_in_exhibition', 'art_from_artist']

class UploadArtist(forms.ModelForm):
    class Meta:
        model = Artist
        exclude = ['artist_uploaded_by','artist_authorised_by']

class UploadExhibition(forms.ModelForm):
    class Meta:
        model = Exhibition
        exclude = ['exhibition_uploaded_by','exhibition_authorised_by']


class UserUpdate(forms.ModelForm):
    class Meta:
        model  = User
        fields = ['username','email']


class UserprofileUpdate(forms.ModelForm):
    class Meta:
        model   = Guidexpuser
        exclude = ['user_type','user']


class createUserForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2',]

class createGuideXPUserForm(forms.ModelForm):
    class Meta:
        model   = Guidexpuser
        exclude = ['user']

back-end/V1/guideXP_admin/views.py
'''import modle for '''
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import (UserUpdate,UserprofileUpdate,UploadArtForm,UploadArtist,createUserForm,createGuideXPUserForm,UploadExhibition)
from .models import Guidexpuser,Artist, Exhibition, Artimage

# def login(request):
#     form = UserCreationForm()
#     return render(request, "guideXP_admin/login.html", {'form':form})
'''This is the the home page '''
@login_required
def home(request):
    return render(request, "guideXP_admin/base.html", {})


'''The forms for the website can be built by dlango automatically, so we just import the libraries that inside 
the Django'''
@login_required
def profile(request):
    u_form = UserUpdate
    p_form = UserprofileUpdate
    context = {
        # user form and user profile form
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, "guideXP_admin/profile.html", context)


'''Creators can create arts after they login'''
@login_required
def createArt(request):
    if request.method == 'POST':
        form               = UploadArtForm(request.POST , request.FILES)
        form1              = UploadArtist(request.POST, request.FILES)
        artist_name        = request.POST.get('artist_name')
        artist_description = request.POST.get('artist_description')
        artist_img         = request.POST.get('artist_img')
        exhibition_name    = request.POST.get('exhibition_name')
        artist             = None
        exhibition         = None
        # check artist name or exhibition name is digit
        if artist_name.isdigit():
            artist = Artist.objects.get(pk=int(artist_name))
        if exhibition_name.isdigit():
            exhibition = Exhibition.objects.get(pk=int(exhibition_name))

        # check form is valid,if the form is  suitable filled,then save it
        if form.is_valid():
            cleaned_data = form.cleaned_data;
            if artist is None:
                if form1.is_valid():
                    cleaned_data_1 = form1.cleaned_data;
                    artist = Artist.objects.create(artist_name=cleaned_data_1.get('artist_name'), artist_img=cleaned_data_1.get('artist_img'),
                                                   artist_description=cleaned_data_1.get('artist_description'), artist_uploaded_by=request.user.guidexpuser)
                    artist.save()
            if exhibition is None:
                exhibition = Exhibition.objects.create(exhibition_name=exhibition_name, exhibition_uploaded_by=request.user.guidexpuser)
                exhibition.save()

            a = Artimage.objects.create(art_name=cleaned_data.get('art_name'), art_description=cleaned_data.get('art_description'),
                                                 art_img = cleaned_data.get('art_img'),art_audio=cleaned_data.get('art_audio'),
                                                 art_in_exhibition = exhibition, art_from_artist = artist, art_uploaded_by = request.user.guidexpuser
                                                 )
            a.save()
            messages.success(request,f'Art has been created!')
            return redirect('admin-upload-art')


    art_form          = UploadArtForm()
    artistForm        = UploadArtist()
    exhibitionForm    = UploadExhibition()
    artists           = Artist.objects.filter(artist_uploaded_by = request.user.guidexpuser)
    exhibitions       = Exhibition.objects.filter(exhibition_uploaded_by = request.user.guidexpuser)
    context_variables = {'form':art_form, 'form1':artistForm, 'form2':exhibitionForm, 'artists':artists, 'exhibitions':exhibitions}
    return render(request,"guideXP_admin/create_art.html", context_variables)


'''Create new Artists'''
@login_required
def createArtist(request):
    artist_form = UploadArtist
    return render(request,"guideXP_admin/create_artist.html", {'form':artist_form})


'''Create login function for admin'''
@login_required
def createAccount(request):
    if request.method == 'POST':
        form1 = createUserForm(request.POST)
        form2 = createGuideXPUserForm(request.POST)
        if form1.is_valid() and form2.is_valid():
            u = User.objects.create_user(username=form1.cleaned_data.get('username'),password=form1.cleaned_data.get('password1'),email=form1.cleaned_data.get('email'))
            u.save()
            guidexpUser = Guidexpuser(user = u,user_type=form2.cleaned_data.get('user_type'))
            guidexpUser.save()
            username = form1.cleaned_data.get('username')
            messages.success(request,f'Account for {username} has been created!')
            return redirect('admin-create-account')
    else:
        userForm        = createUserForm()
        guidexpUserform = createGuideXPUserForm()
    return render(request,"guideXP_admin/create_account.html", {'form1':userForm,'form2':guidexpUserform,})

back-end/V1/guideXP_admin/templates/guideXP_admin/base.html
{#this is the base template for all the pages#}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <!-- css -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'guideXP_admin/css/main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    {% block css %}
    {% endblock %}
    <!-- js -->
    <script type="text/javascript" src="{% static 'jquery-3.4.1.slim.js' %}"></script>
    <script type="text/javascript" src="{% static 'popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'guideXP_admin/js/main.js' %}"></script>
    <style>
        .my-container{
            border:1px solid green;
        }

        .my-row{
            border:3px solid red;
        }

        .my-col{
            border:3px solid blue;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'admin-home' %}">GuideXP</a>
      {% if user.is_authenticated %}
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Create</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'admin-upload-art' %}">new art</a>
{#                    <a class="dropdown-item" href="#">new gallery</a>#}
{#                    <a class="dropdown-item" href="#">new exhibition</a>#}
{#                    <a class="dropdown-item" href="{% url 'admin-upload-artist' %}">new artist</a>#}
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Edit</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Edit previous uploads</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Setting</a>
                <div class="dropdown-menu" aria-labelledby="dropdown02">
                    <a class="dropdown-item" href="{% url 'admin-profile' %}">My profile</a>
                    <a class="dropdown-item" href="#">Change password</a>
                    {% if user.guidexpuser.user_type == '1' %}
                    <a class="dropdown-item" href="{% url 'admin-create-account' %}">Create account</a>
                    {% endif %}
                </div>
              </li>
              <li class="nav-item"><a class="nav-link" href="{% url 'admin-logout' %}">Log out</a></li>
            </ul>
          </div>
      {% endif %}
    </nav>
    <div class="container mt-5">
    <div class="row mb-3 ">
        <div class="col-3 "></div>
        <div class="col-6 ">{% block content %}{% endblock %}</div>
        <div class="col-3 "></div>
    </div>
    </div>

</body>
</html>

back-end/V1/guideXP_admin/templates/guideXP_admin/create_account.html
{% extends 'guideXP_admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <form method = "POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add Account</legend>
{#            some forms to upload #}
            {{form2|crispy}}
            {{form1|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-secondary btn-lg btn-block" type="submit">Add</button>
        </div>
    </form>
{% endblock %}

back-end/V1/guideXP_admin/templates/guideXP_admin/create_art.html
{#Load the basic template#}
{% extends 'guideXP_admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="row">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    </div>



    <form method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Upload art</legend>
            {{form|crispy}}
        </fieldset>


       <div class="form-group">
           <button class="btn btn-outline-secondary btn-lg btn-block" data-toggle="collapse" data-target="#showArtistForm" type="button">Add Artist</button>
           <div class="collapse" id="showArtistForm">
            <div class="card card-body">
                <select class="custom-select" id="artist-select" autocomplete="off">
                  <option value="ignore" selected>Select stored artist...</option>
                    {% for artist in artists %}
                        <option value="{{artist.id}}" id="artist-select-{{artist.id}}">{{artist.artist_name}}</option>
                    {% endfor %}
                </select>
                <div class="form-group mt-5" id="artist-form">
                    {{form1|crispy}}
                </div>
                {% for artist in artists %}
                    <div id="artist-details-{{artist.id}}" style="display: none" class="mt-4 text-center">
                        <img id="artist-details-img" src="{{artist.artist_img.url}}" class="rounded-circle img-fluid w-50">
                        <p id="artist-detail-name" class="text-black font-weight-bold mt-3 text-uppercase artist-name" >{{artist.artist_name}}</p>
                    </div>
                {% endfor %}
            </div>
           </div>
        </div>

       <div class="form-group">
           <button class="btn btn-outline-secondary btn-lg btn-block" data-toggle="collapse" data-target="#showExhibitionForm" type="button">Add Exhibition</button>
           <div class="collapse" id="showExhibitionForm">
               <div class="card card-body">
                   <select class="custom-select" id="exhibition-select" autocomplete="off">
                       <option value="ignore" selected>Select stored exhibitions...</option>
                        {% for exhibition in exhibitions %}
                            <option value="{{exhibition.id}}" id="exhibition-select-{{exhibition.id}}">{{exhibition.exhibition_name}}</option>
                        {% endfor %}
                   </select>
                   <div class="form-group mt-5" id="exhibition-form">
                        {{form2|crispy}}
                   </div>
                   {% for artist in artists %}
                       <div id="exhibition-details-{{exhibition.id}}" style="display: none" class="mt-4 text-center">
                            <p id="exhibition-detail-name" class="text-black font-weight-bold mt-3 text-uppercase artist-name" >{{exhibition.exhibition_name}}</p>
                       </div>
                   {% endfor %}
               </div>
           </div>
        </div>


        <div class="form-group">
            <button class="btn btn-outline-secondary btn-lg btn-block" type="submit">Upload</button>
        </div>
    </form>



{% endblock %}

back-end/V1/guideXP_admin/templates/guideXP_admin/create_artist.html
{% extends 'guideXP_admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <form method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add a new artist</legend>
            {{form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-secondary btn-lg btn-block" type="submit">Add</button>
        </div>
    </form>
{% endblock %}

back-end/V1/guideXP_admin/templates/guideXP_admin/login.html
{% extends 'guideXP_admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method = "POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-secondary btn-lg btn-block" type="submit">Login</button>
        </div>
    </form>
{% endblock %}

back-end/V1/guideXP_admin/templates/guideXP_admin/logout.html
{% extends 'guideXP_admin/base.html' %}
{% block content %}
    <div class="container-fluid">
        <h2>You have been logged out</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'admin-login' %}">Log In Again</a>
            </small>
        </div>
    </div>
{% endblock %}

back-end/V1/guideXP_admin/templates/guideXP_admin/profile.html
{% extends 'guideXP_admin/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="media">
        <div class="media-body">
            <h2 class="text-uppercase">{{user.username}}</h2>
            <p class="text-secondary">{{user.email}}</p>
            <p class="text-secondary">{{user.guidexpuser.get_user_type_display}}</p>
        </div>
    </div>
    <form method = "POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Update Profile</legend>
            {{u_form|crispy}}
            {{p_form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-secondary btn-lg btn-block" type="submit">Update</button>
        </div>
    </form>
{% endblock %}